### ISSUE TITLE
Kind Cluster Customization/Further Config Options

### ISSUE THREAD

**Issue by corinz** [knative-sandbox/kn-plugin-quickstart#337]
A typical Kind cluster config that is prepared for ingress may look something like this:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 30000
    hostPort: 5432
    protocol: TCP
```

Is there a plan to augment the existing quickstart cluster to accept other kind/minikube customizations? Is it possible to point quickstart to existing clusters?
